/*
const isResolved = true;

const promise = new Promise((resolve, reject) => {
    if (isResolved) {
        resolve('completed');
    } else {
        reject(new Error('something went wrong'));
    }
});

console.log(promise);

promise.catch(() => {
    console.log('error');
}).then((result) => console.log(result));
*/

